# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('cachecast', ['core'])
    module.source = [
        'model/cachecast.cc',
        'model/cachecast-header.cc',
        'helper/cachecast-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('cachecast')
    module_test.source = [
        'test/cachecast-test-suite.cc',
        ]

    headers = bld.new_task_gen(features=['ns3header'])
    headers.module = 'cachecast'
    headers.source = [
        'model/cachecast.h',
        'model/cachecast-header.h',
        'helper/cachecast-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.add_subdirs('examples')

    # bld.ns3_python_bindings()

