# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('cachecast-example2', ['cachecast', 'network', 'internet', 'applications'])
    obj.source = 'cachecast-example2.cc'

    obj = bld.create_ns3_program('cachecast-example3', ['cachecast', 'network', 'internet', 'applications'])
    obj.source = 'cachecast-example3.cc'
